### ISSUE TITLE
Nullpointer Exception when starting scala kernel

### ISSUE THREAD

**Issue by Ycallaer** [jupyter-scala/jupyter-scala#179]
Hi,
I just installed the scala kernel as suggested in the readme but I'm getting a nullpointer exception when the scala kernel starts

Configuration:
* Jupyter notebook  version: 4.4.0
* OS: Mac os Sierra
* Jupyter-scala: current master branch
* Java: 
java 9.0.1
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

I start jupyter notebook with `jupyter notebook`

If I create a new notebook and select the scala kernel I get the following stacktrace

`[W 13:57:09.056 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180102135702 (::1) 1.92ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=scala
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at jupyter.kernel.server.ServerApp$.apply(ServerApp.scala:174)
	at jupyter.scala.JupyterScalaApp.delayedEndpoint$jupyter$scala$JupyterScalaApp$1(JupyterScala.scala:93)
	at jupyter.scala.JupyterScalaApp$delayedInit$body.apply(JupyterScala.scala:13)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at caseapp.App$$anonfun$apply$1.apply(App.scala:47)
	at caseapp.App$$anonfun$apply$1.apply(App.scala:46)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at caseapp.App$class.apply(App.scala:46)
	at jupyter.scala.JupyterScalaApp.apply(JupyterScala.scala:13)
	at caseapp.AppOf.main(App.scala:121)
	at jupyter.scala.JupyterScala.main(JupyterScala.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at coursier.cli.qJ.a(Unknown Source)
	at coursier.cli.qI.j(Unknown Source)
	at coursier.cli.qO.a(Unknown Source)
	at d.g.a.c(Unknown Source)
	at b.b.d_(Unknown Source)
	at d.b.d.E.g(Unknown Source)
	at d.b.e.aU.g(Unknown Source)
	at a.c.a(Unknown Source)
	at coursier.cli.qI.b(Unknown Source)
	at coursier.cli.O.b(Unknown Source)
	at b.I.d_(Unknown Source)
	at d.E.h(Unknown Source)
	at a.aH.a(Unknown Source)
	at coursier.cli.Coursier.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at coursier.Bootstrap.main(Bootstrap.java:412)`

Any help would be appreciated

**Comment by Ycallaer** [comment]
Seems to have resolved after reinstalling
