### ISSUE TITLE
Kernel Dies on Startup

### ISSUE THREAD

**Issue by ashkan-leo** [jupyter-scala/jupyter-scala#188]
I installed the kernel using the jupyter-scala script. Everytime I open an Scala notebook, the notebook dies instantly. I get the following exceptions on the terminal:
```
kernel bea5eb89-f678-4a42-9c23-b28529f1084d restarted
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at jupyter.kernel.server.ServerApp$.apply(ServerApp.scala:174)
	at jupyter.scala.JupyterScalaApp.delayedEndpoint$jupyter$scala$JupyterScalaApp$1(JupyterScala.scala:93)
	at jupyter.scala.JupyterScalaApp$delayedInit$body.apply(JupyterScala.scala:13)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at caseapp.App$$anonfun$apply$1.apply(App.scala:47)
	at caseapp.App$$anonfun$apply$1.apply(App.scala:46)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at caseapp.App$class.apply(App.scala:46)
	at jupyter.scala.JupyterScalaApp.apply(JupyterScala.scala:13)
	at caseapp.AppOf.main(App.scala:121)
	at jupyter.scala.JupyterScala.main(JupyterScala.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at coursier.cli.qJ.a(Unknown Source)
	at coursier.cli.qI.j(Unknown Source)
	at coursier.cli.qO.a(Unknown Source)
	at d.g.a.c(Unknown Source)
	at b.b.d_(Unknown Source)
	at d.b.d.E.g(Unknown Source)
	at d.b.e.aU.g(Unknown Source)
	at a.c.a(Unknown Source)
	at coursier.cli.qI.b(Unknown Source)
	at coursier.cli.O.b(Unknown Source)
	at b.I.d_(Unknown Source)
	at d.E.h(Unknown Source)
	at a.aH.a(Unknown Source)
	at coursier.cli.Coursier.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at coursier.Bootstrap.main(Bootstrap.java:412)
Caused by: java.lang.NullPointerException
	at ammonite.runtime.Classpath$.classpath(Classpath.scala:31)
	at ammonite.interp.Interpreter.init(Interpreter.scala:93)
	at ammonite.interp.Interpreter.processModule(Interpreter.scala:409)
	at ammonite.interp.Interpreter$$anonfun$10.apply(Interpreter.scala:151)
	at ammonite.interp.Interpreter$$anonfun$10.apply(Interpreter.scala:148)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at ammonite.interp.Interpreter.<init>(Interpreter.scala:148)
	at jupyter.scala.Interp$$anon$3.<init>(Interp.scala:41)
	at jupyter.scala.Interp.<init>(Interp.scala:41)
	at jupyter.scala.JupyterScalaApp$$anon$5.apply(JupyterScala.scala:98)
	at jupyter.scala.JupyterScalaApp$$anon$5.apply(JupyterScala.scala:97)
	at jupyter.kernel.server.Server$.launch(Server.scala:80)
	at jupyter.kernel.server.Server$.apply(Server.scala:123)
	at jupyter.kernel.server.ServerApp$$anonfun$4.apply(ServerApp.scala:171)
	at jupyter.kernel.server.ServerApp$$anonfun$4.apply(ServerApp.scala:171)
	at scala.util.Try$.apply(Try.scala:192)
	at jupyter.kernel.server.ServerApp$.apply(ServerApp.scala:171)
	... 36 more
``` 

I am using Jupyter version 4.4.0. I appreciate if someone could point me to the right direction to fix this issue.

**Comment by keithschulze** [comment]
@ashkan-leo this appears to happen with Java 9 and 10. Switching back to Java 8 solves it for me. If you have multiple Java versions installed, you can select Java 8 using the JAVA_HOME environment variable:

```
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
```

**Comment by ashkan-leo** [comment]
Thanks a lot. That solved the issue!

**Comment by OOPMan** [comment]
@keithschulze There should be a note about this in the README :-)

**Comment by anish749** [comment]
I spent almost a whole day searching for this page...!!! Yes there should be a mention in the README.
