### ISSUE TITLE
ipython3 console --kernel scala210: type "load" and press tab

### ISSUE THREAD

**Issue by gavrmike** [jupyter-scala/jupyter-scala#24]
Hi!

I just install jupyter-scala and when i try write "load" and press tab i always get: "kernel died, restart ([y]/n)?"

And backtrace:
In [3]: loadException in thread "main" java.lang.UnsupportedOperationException: Position.end on class scala.reflect.internal.util.OffsetPosition
    at scala.reflect.internal.util.Position.end(Position.scala:126)
    at ammonite.interpreter.Pressy$Run.prefixed(Pressy.scala:80)
    at ammonite.interpreter.Pressy$$anon$3.complete(Pressy.scala:175)
    at ammonite.interpreter.Interpreter.complete(Interpreter.scala:155)
    at jupyter.scala.ScalaInterpreter$$anon$1.complete(ScalaInterpreter.scala:170)
    at jupyter.kernel.interpreter.InterpreterHandler$.complete(InterpreterHandler.scala:159)
    at jupyter.kernel.interpreter.InterpreterHandler$.apply(InterpreterHandler.scala:233)
    at jupyter.kernel.server.InterpreterServer$$anonfun$1.apply(InterpreterServer.scala:87)
    at jupyter.kernel.server.InterpreterServer$$anonfun$1.apply(InterpreterServer.scala:82)
    at scalaz.stream.Process$$anonfun$map$1.apply(Process.scala:47)
    at scalaz.stream.Process$$anonfun$map$1.apply(Process.scala:47)
    at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:40)
    at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:40)
    at scalaz.stream.Util$.Try(Util.scala:42)
    at scalaz.stream.Process$class.flatMap(Process.scala:40)
    at scalaz.stream.Process$Emit.flatMap(Process.scala:571)
    at scalaz.stream.Process$$anonfun$flatMap$3.apply(Process.scala:41)
    at scalaz.stream.Process$$anonfun$flatMap$3.apply(Process.scala:41)
    at scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
    at scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
    at scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
    at scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
    at scalaz.Free.resume(Free.scala:72)
    at scalaz.Free.go2$1(Free.scala:118)
    at scalaz.Free.go(Free.scala:122)
    at scalaz.Free.run(Free.scala:172)
    at scalaz.stream.Process$$anonfun$go$3$3$$anonfun$6.apply(Process.scala:473)
    at scalaz.stream.Process$$anonfun$go$3$3$$anonfun$6.apply(Process.scala:473)
    at scalaz.stream.Util$.Try(Util.scala:42)
    at scalaz.stream.Process$$anonfun$go$3$3.apply(Process.scala:473)
    at scalaz.stream.Process$$anonfun$go$3$3.apply(Process.scala:472)
    at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:36)
    at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:36)
    at scalaz.concurrent.Task$.Try(Task.scala:379)
    at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:36)
    at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:34)
    at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:59)
    at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:59)
    at scalaz.concurrent.Future.step(Future.scala:111)
    at scalaz.concurrent.Future.listen(Future.scala:76)
    at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
    at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
    at scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
    at scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
    at scalaz.Free.resume(Free.scala:73)
    at scalaz.Free.go2$1(Free.scala:118)
    at scalaz.Free.go(Free.scala:122)
    at scalaz.Free.run(Free.scala:172)
    at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:367)
    at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:367)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

If i type something else it works.

**Comment by alexarchambault** [comment]
Looks like an issue with the presentation compiler... I hope it'll go away once the project will get an update.

**Comment by alexarchambault** [comment]
Closing this now that the [upcoming version](https://github.com/jupyter-scala/jupyter-scala/tree/develop) is about to become the default one.
