### ISSUE TITLE
Scalatest 3.0 - exception during macro expansion

### ISSUE THREAD

**Issue by chilang** [jupyter-scala/jupyter-scala#40]
Hi,

I'm getting error while trying to use Scalatest 3.0 M14 in jupyter-scala@master:

```
load.ivy("org.scalatest" %% "scalatest" % "3.0.0-M14")
import org.scalatest.Assertions
import org.scalatest.Assertions.assertionsHelper
Assertions.assert(2 == 2)
```

produces:

```
Compilation Failed
Main.scala:53: exception during macro expansion: 
scala.reflect.macros.TypecheckException: not found: value assertionsHelper
    at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2$$anonfun$apply$1.apply(Typers.scala:34)
    at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2$$anonfun$apply$1.apply(Typers.scala:28)
    at scala.reflect.macros.contexts.Typers$$anonfun$3.apply(Typers.scala:24)
    at scala.reflect.macros.contexts.Typers$$anonfun$3.apply(Typers.scala:24)
    at scala.reflect.macros.contexts.Typers$$anonfun$withContext$1$1.apply(Typers.scala:25)
    at scala.reflect.macros.contexts.Typers$$anonfun$withContext$1$1.apply(Typers.scala:25)
    at scala.reflect.macros.contexts.Typers$$anonfun$1.apply(Typers.scala:23)
    at scala.reflect.macros.contexts.Typers$$anonfun$1.apply(Typers.scala:23)
    at scala.reflect.macros.contexts.Typers$class.withContext$1(Typers.scala:25)
    at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2.apply(Typers.scala:28)
    at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2.apply(Typers.scala:28)
    at scala.reflect.internal.Trees$class.wrappingIntoTerm(Trees.scala:1716)
    at scala.reflect.internal.SymbolTable.wrappingIntoTerm(SymbolTable.scala:16)
    at scala.reflect.macros.contexts.Typers$class.withWrapping$1(Typers.scala:26)
    at scala.reflect.macros.contexts.Typers$class.typecheck(Typers.scala:28)
    at scala.reflect.macros.contexts.Context.typecheck(Context.scala:6)
    at scala.reflect.macros.contexts.Context.typecheck(Context.scala:6)
    at scala.reflect.macros.Typers$class.typeCheck(Typers.scala:58)
    at scala.reflect.macros.contexts.Context.typeCheck(Context.scala:6)
    at org.scalactic.MacroOwnerRepair.repairOwners(MacroOwnerRepair.scala:35)
    at org.scalactic.BooleanMacro.genMacro(BooleanMacro.scala:814)
    at org.scalatest.AssertionsMacro$.assert(AssertionsMacro.scala:34)

Assertions.assert(2 == 2)
```

The same code works fine in standard scala console (2.11.6) or original ammonite-repl (but also fails on the last working revision of your ammonite https://github.com/alexarchambault/ammonite-shell/commit/95a62267d52b37b4bcc34771eff04002d053dac0)

Any ideas?

**Comment by alexarchambault** [comment]
I get the same error too.

My best guess would be that the problem originates from the class loader used for macros, that is given to the compiler [here](https://github.com/alexarchambault/ammonite-shell/blob/c4d4af63e8249bda63875b849dbb69bdfa53ba62/interpreter/src/main/scala/ammonite/interpreter/Interpreter.scala#L372)... It should lack some libraries, although I don't see why or how it does. The original Ammonite does all of this differently as it doesn't do class loader isolation like here.

FYI I think I'll rework this part of the code when I'll integrate [coursier](https://github.com/alexarchambault/coursier). I'll have a look then if it can't be fixed in the mean time.

**Comment by alexarchambault** [comment]
Closing, that seems to work fine with the upcoming version (currently on the [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop)).
