### ISSUE TITLE
ipython kernelspec list not work (No module named zmq)

### ISSUE THREAD

**Issue by samthebest** [jupyter-scala/jupyter-scala#41]
```
> ipython kernelspec list

Traceback (most recent call last):
  File "/usr/bin/ipython", line 6, in <module>
    start_ipython()
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-111>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "/usr/local/lib/python2.7/dist-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
ImportError: No module named zmq
```

**Comment by samthebest** [comment]
If anyone else gets this issue, the way I managed to solve the issues was:

```
sudo apt-get -y install ipython
sudo apt-get -y install python-pip

sudo apt-get update && sudo apt-get install python3-dev python3-pip build-essential libzmq3-dev
sudo pip3 install virtualenv
virtualenv -p $(which python3) myenv
source myenv/bin/activate
sudo pip3 install pyzmq
python3 -c 'import zmq; print(zmq.zmq_version())'

sudo pip3 install --upgrade "ipython[all]"

wget https://oss.sonatype.org/content/repositories/snapshots/com/github/alexarchambault/jupyter/jupyter-scala-cli_2.11.6/0.2.0-SNAPSHOT/jupyter-scala_2.11.6-0.2.0-SNAPSHOT.zip

unzip jupyter-scala_2.11.6-0.2.0-SNAPSHOT.zip

chmod +x jupyter-scala_2.11.6-0.2.0-SNAPSHOT/bin/jupyter-scala

sudo pip3 install jupyter_console

```

Finally to then run the notebook:

```
ipython3 notebook
```

**Comment by alexarchambault** [comment]
@samthebest Thanks for the report, more an ipython installation issue than a jupyter-scala one, but this kind of things might be worth mentioning in a future update of the documentation of jupyter-scala.
